pipeline {
	agent any
	stages {

		stage('Lint HTML') {
			steps {
				
				sh '''
					cd Deploy-containers-pipeline
					tidy -q -e *.html
				'''
			}
		}
		
		stage('Build Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						cd Deploy-containers-pipeline
						docker build -t bcsalinasc/capstone .
					'''
				}
			}
		}

		stage('Push Image To Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						cd Deploy-containers-pipeline
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
						docker push bcsalinasc/capstone
					'''
				}
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscapstone') {
					sh '''
						cd Deploy-containers-pipeline
						kubectl config use-context arn:aws:eks:us-west-2:143134632908:cluster/capstonecluster
					'''
				}
			}
		}

		stage('Deploy blue container') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscapstone') {
					sh '''
						cd Deploy-containers-pipeline
						kubectl apply -f ./blue-controller.json
					'''
				}
			}
		}

		stage('Deploy green container') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscapstone') {
					sh '''
						cd Deploy-containers-pipeline
						kubectl apply -f ./green-controller.json
					'''
				}
			}
		}

		stage('Create the service in the cluster, redirect to blue') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscapstone') {
					sh '''
						cd Deploy-containers-pipeline
						kubectl apply -f ./blue-service.json
					'''
				}
			}
		}

		stage('Wait user approve') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('Create the service in the cluster, redirect to green') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscapstone') {
					sh '''
						cd Deploy-containers-pipeline
						kubectl apply -f ./green-service.json
					'''
				}
			}
		}

	}
}
